name: Daily Commit Summary

on:
  schedule:
    - cron: '0 18 * * *'  # À 18h UTC tous les jours, ajustable selon tes besoins

jobs:
  discord_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch commit data
        run: |
          commits=$(git log --since="yesterday" --pretty=format:"* %h - %s (%an)" --abbrev-commit)
          if [ -z "$commits" ]; then
            echo "No commits found in the last 24 hours." > commit_message.txt
          else
            echo "Derniers commits:\n$commits" > commit_message.txt
          fi

      - name: Send daily summary to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
                "username": "GitHub Summary",
                "avatar_url": "https://path.to/your/avatar.png",
                "embeds": [{
                    "title": "Résumé des commits d’hier",
                    "description": "$(cat commit_message.txt)",
                    "color": 16711680,  # Code couleur pour un rouge
                    "footer": {
                      "text": "GitHub Actions",
                      "icon_url": "https://path.to/footer/icon.png"
                    },
                    "timestamp": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
                }]
              }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
